### ISSUE TITLE
Fail to build on Ubuntu 18.04 ppc64le

### ISSUE THREAD

**Issue by tzafrir-mellanox** [openucx/xpmem#27]
Building recent master (93ae5ca9d3451ae25ee814ddc80b9bc4ff081b5f) on Ubuntu 18.04 fails:
  CC [M]  /var/lib/dkms/xpmem/2.6.5/build/kernel/xpmem_mmu_notifier.o
In file included from ./include/linux/kernel.h:10:0,
                 from ./include/linux/list.h:9,
                 from ./include/linux/module.h:9,
                 from /var/lib/dkms/xpmem/2.6.5/build/kernel/xpmem_mmu_notifier.c:13:
./arch/powerpc/include/asm/uaccess.h: In function ‘clear_user’:
./arch/powerpc/include/asm/uaccess.h:437:23: error: ‘VERIFY_WRITE’ undeclared (first use in this function); did you mean ‘MAY_WRITE’?
  if (likely(access_ok(VERIFY_WRITE, addr, size))) {
                       ^
(Log attached)
